### ISSUE TITLE
Unable to play anything "Sorry, something went wrong"

### ISSUE THREAD

**Issue by kokarn** [gillesdemey/Cumulus#14]
Worked yesterday with 0.4.0, still running the same version but is borked now :/

Running as a developer gives me this log:
https://gist.github.com/kokarn/7c2f55a7fa5e7dd84de1

**Comment by gillesdemey** [comment]
What tab does this occur in? Does this happen right after you open the app?

**Comment by kokarn** [comment]
It happens in all the tabs, but I only see the loading on the first one.

Yes, it happens right away :/

**Comment by kokarn** [comment]
Wow, it's been broken for a week but now it works for some reason.

Not sure if it mattered but I pressed "like" directly when it started if there was something wrong with the feed page.

It works when I restart and stay on feed tho, so might've been something else entirely :/

**Comment by kokarn** [comment]
This is still an issue apparently. It worked for a couple of weeks and then it started doing the same thing again. 
I'm now on 0.5.2 and I either get "Sorry, something went wrong" or it loads forever. 
If i get the message, the loading finishes in like 1s.

Anything i can do to help debug?

**Comment by xnutsive** [comment]
0.5.3, seeing “something went wrong” only on the feed tab.

**Comment by gillesdemey** [comment]
Hey guys,

I'm trying to replicate this bug — but have been unable for a while.
Can you run the app in debug mode and report the error log? The instructions are in the README.

If anything is unclear feel free to ask question.

**Comment by mutewinter** [comment]
Also seeing this bug for the last week. I deleted the app and all supporting files, reinstalled, still "Sorry, something went wrong" only on the feed tab. App had been working for weeks and suddenly stopped. I'll run in debug mode and report back once I get a moment.

**Comment by gillesdemey** [comment]
I think I've figured this one out. I've just recently ran into a weird edge-case myself. I've just released a new version — let me know if that fixes the issue for you.

https://github.com/gillesdemey/Cumulus/releases/tag/v0.5.4

**Comment by kokarn** [comment]
I'll close this for now and if it reappears i'll re-open it.

Thanks for having a look!

**Comment by mutewinter** [comment]
Also confirmed fixed.

**Comment by loicnestler** [comment]
This bug still seems to exist on my MBP M1 Pro running MacOS 14.0. :/
![SCR-20240408-grf](https://github.com/gillesdemey/Cumulus/assets/48695625/4fa89098-b234-4112-95c4-a364c375a1ba)

EDIT: Removed 2 screenshots as they showed up quite large; the content is the same on all 3 tabs.
